name: Dune Build Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '5.1.1'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install dependencies and build
        run: |
          opam install . --deps-only --with-test
          eval $(opam env)
          dune build

      - name: Check for unclean workspace
        run: git diff --exit-code
